import mongoose, { Schema, Document } from 'mongoose';

/**
 * Certificate Interface
 * This is the off-chain cached representation of the On-Chain Provenance Certificate.
 * It allows fast querying for the frontend without hitting the Stellar RPC constantly.
 */
export interface ICertificate extends Document {
  verificationJobId: mongoose.Types.ObjectId;
  assetId: mongoose.Types.ObjectId;
  manifestId: mongoose.Types.ObjectId;
  creatorId: mongoose.Types.ObjectId;
  
  // On-Chain Data References
  stellarNetwork: 'testnet' | 'mainnet';
  contractAddress: string;       // The Soroban Provenance Certificate Contract ID
  certificateId: string;         // Unique ID generated by the smart contract
  transactionHash: string;       // Hash of the minting transaction
  ledgerSequence: number;        // The Stellar ledger block where this was minted
  
  mintedAt: Date;                // Blockchain timestamp
  createdAt: Date;
  updatedAt: Date;
}

const CertificateSchema: Schema = new Schema(
  {
    verificationJobId: {
      type: Schema.Types.ObjectId,
      ref: 'VerificationJob',
      required: true,
      unique: true, // One job = One certificate
    },
    assetId: {
      type: Schema.Types.ObjectId,
      ref: 'Asset',
      required: true,
    },
    manifestId: {
      type: Schema.Types.ObjectId,
      ref: 'Manifest',
      required: true,
    },
    creatorId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    stellarNetwork: {
      type: String,
      enum: ['testnet', 'mainnet'],
      required: true,
      default: 'testnet',
    },
    contractAddress: {
      type: String,
      required: true,
    },
    certificateId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    transactionHash: {
      type: String,
      required: true,
      index: true,
    },
    ledgerSequence: {
      type: Number,
      required: true,
    },
    mintedAt: {
      type: Date,
      required: true,
    }
  },
  { timestamps: true }
);

export default mongoose.model<ICertificate>('Certificate', CertificateSchema);
